app/models/food_cart.rb, app/models/menu.rb, db/migrate/20210325115708_create_food_carts.rb, db/migrate/20210325122714_remove_column_from_food_cart.rb, db/migrate/20210325123336_add_open_to_food_carts.rb, db/migrate/20210325124652_create_menus.rb, db/migrate/20210325125645_add_column_to_menu.rb, db/schema.rb, test/models/food_cart_test.rb, test/models/menu_test.rb
@worksofgenius please check and merge what we have done already
=> food cart model & menu model partially done

app/models/food_cart.rb, app/models/menu.rb, app/models/schedule.rb, db/migrate/20210325115708_create_food_carts.rb, db/migrate/20210325122714_remove_column_from_food_cart.rb, db/migrate/20210325123336_add_open_to_food_carts.rb, db/migrate/20210325124652_create_menus.rb, db/migrate/20210325125645_add_column_to_menu.rb, db/migrate/20210330101938_add_food_cart_ref_to_menu.rb, db/migrate/20210330103518_add_ref_user_to_food_carts.rb, db/migrate/20210330105243_create_schedules.rb, db/migrate/20210330105837_add_schedule_ref_to_food_carts.rb, db/migrate/20210330113741_remove_column_from_food_carts.rb, db/migrate/20210330113949_add_ref_food_cart_to_schedule.rb, db/schema.rb, test/models/food_cart_test.rb, test/models/menu_test.rb, test/models/schedule_test.rb
=> Modelupdates

app/models/food_item.rb, db/migrate/20210330115449_create_food_items.rb, db/schema.rb, test/models/food_item_test.rb
=> food_item Model added

app/controllers/application_controller.rb, app/models/food_item.rb, app/models/user.rb, db/migrate/20210330115449_create_food_items.rb, db/migrate/20210330121824_add_admin_to_users.rb, db/migrate/20210330122229_add_first_name_to_users.rb, db/migrate/20210330122313_add_last_name_to_users.rb, db/migrate/20210330122432_add_phone_number_to_users.rb, db/migrate/20210330122844_add_ref_food_cart_to_users.rb, db/schema.rb, test/models/food_item_test.rb
=> Updated user model

app/controllers/application_controller.rb, config/routes.rb
=> added routes

app/controllers/food_carts_controller.rb, app/controllers/food_items_controller.rb, test/controllers/food_carts_controller_test.rb, test/controllers/food_items_controller_test.rb
=> added foodcart and fooditem controllers

Gemfile.lock, app/controllers/menu_controller.rb, app/controllers/schedules_controller.rb, test/controllers/menu_controller_test.rb, test/controllers/schedules_controller_test.rb
=> menu and schedule controller outline

app/controllers/application_controller.rb, app/controllers/menu_controller.rb, app/controllers/schedules_controller.rb, app/policies/menu_policy.rb, app/policies/schedule_policy.rb, package-lock.json, test/policies/menu_policy_test.rb, test/policies/schedule_policy_test.rb, test/policies/schedules_policy_test.rb
=> pundit policies added for menu and schedules

app/javascript/packs/FoodCarts/show.jsx, app/views/food_carts/show.html.erb
Converted food_carts show view to React component
=> converted food_carts#show to React

app/controllers/food_carts_controller.rb, app/views/food_carts/index.html.erb
=> destroy method working for food carts index

app/controllers/food_carts_controller.rb, app/controllers/schedules_controller.rb, app/views/food_carts/index.html.erb, app/views/food_carts/show.html.erb, app/views/schedules/new.html.erb
=> menu issues

Gemfile
=> Dotenv gem

.gitignore, Gemfile, Gemfile.lock
=> added cloudinary gem

app/controllers/food_carts_controller.rb, app/controllers/menu_controller.rb, app/controllers/schedules_controller.rb, app/policies/schedule_policy.rb, app/views/food_carts/show.html.erb, app/views/schedules/new.html.erb, config/routes.rb
@brandon-lindberg  issues with pundit policy need to be resolved
=> updated routes and controllers on schedule

app/controllers/food_carts_controller.rb, app/controllers/food_items_controller.rb, app/views/food_carts/show.html.erb, app/views/food_items/new.html.erb
=> menu new page added

app/controllers/food_items_controller.rb, app/views/food_items/new.html.erb, app/views/menus/show.html.erb
=> in process food items adding, error on new

app/controllers/food_carts_controller.rb, app/controllers/menus_controller.rb, app/controllers/schedules_controller.rb, app/views/food_carts/show.html.erb, app/views/schedules/index.html.erb
=> Schedule update

app/controllers/food_carts_controller.rb, app/controllers/schedules_controller.rb, app/models/schedule.rb, app/policies/application_policy.rb, app/policies/schedule_policy.rb, app/views/food_carts/show.html.erb, app/views/schedules/edit.html.erb, app/views/schedules/index.html.erb
=> fixed pundit issues with Marisa and Dan

app/assets/stylesheets/components/_cards.scss, app/javascript/packs/FoodCarts/show.jsx, app/javascript/packs/FoodItems/foodItemCard.jsx, yarn.lock
Link icon to food cart schedule page.
=> Add image to flex card on food cart show page

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_menu.scss, app/javascript/packs/FoodCarts/show.jsx
=> Debug icons container on foodcart show page

app/policies/food_item_policy.rb, app/policies/schedule_policy.rb
=> Added policy for admin || employees for food items and schedule

db/migrate/20210608113749_change_time_to_date_time.rb, db/migrate/20210608120036_add_start_time_to_schedules.rb, db/schema.rb, db/seeds.rb
=> changed time to datetime

Gemfile, Gemfile.lock, app/controllers/food_carts_controller.rb, app/models/food_cart.rb, app/models/user.rb, config/routes.rb, db/migrate/20210610123526_acts_as_votable_migration.rb, db/schema.rb
=> added act as a vote gem

app/controllers/food_carts_controller.rb, app/javascript/packs/FoodCarts/foodCartIsOpen.js, app/javascript/packs/FoodCarts/index.jsx, app/javascript/packs/FoodCarts/marker.jsx, app/javascript/packs/MainTemplate.jsx, app/views/food_carts/index.html.erb
=> Refactored

app/controllers/food_carts_controller.rb, app/javascript/packs/FoodCarts/FoodCartCard.jsx, app/javascript/packs/FoodCarts/Show.jsx, app/javascript/packs/FoodCarts/index.jsx, app/javascript/packs/MainTemplate.jsx, app/javascript/packs/Schedules/index.jsx, app/javascript/packs/entry.jsx, app/views/food_carts/index.html.erb, app/views/food_carts/show.html.erb
changed order in which food carts appear in food_carts#index
liked and open 👉 not liked, but open 👉 liked and closed 👉 not liked and closed
=> Food carts index order

app/views/layouts/application.html.erb
Expand title tag to 20+ character to improve SEO
=> Improve title for SEO

app/controllers/registrations_controller.rb, config/environments/production.rb
=> initial push to heroku

app/controllers/registrations_controller.rb
=> Changed registrations controller

app/javascript/packs/FoodItems/foodItemCard.jsx, app/javascript/packs/entry.jsx, config/locales/en.json, config/locales/jp.json
=> Delete excluding tax

app/javascript/packs/FoodCarts/FoodCartCard.jsx, app/javascript/packs/FoodCarts/New.jsx, app/javascript/packs/FoodCarts/Show.jsx, app/javascript/packs/FoodCarts/foodCartIsOpen.js, app/javascript/packs/Helper/getFoodItemCard.jsx, app/javascript/packs/Navbar.jsx, app/javascript/packs/Schedules/DayCard.js, app/javascript/packs/Schedules/DetailedSchedule.jsx, app/javascript/packs/Schedules/index.jsx, app/javascript/packs/Schedules/new.js, app/javascript/packs/entry.jsx, app/javascript/plugins/geolocation.js, app/javascript/plugins/init_mapbox.js
Well that one was a bugger. Apparently we had a regex that Safari doesn't support. Since all Apple mobiles run on Webkit that explains why it didn't work on any of our phones.
=> Fix mobile and remove console logs

app/javascript/packs/Pages/Title.jsx, app/javascript/packs/entry.jsx
=> committed to updating the copyright date
